#!/bin/bash
#
# Used to convert all submissions to a PDF. 
# Looks through all the directories in the current directory, and
# if there's a file inside with given filename, generates a PDF in
# that output directory.
# 
# Do not need file extension in filename (assuming it is always .py)
# 
# PDF generation is done via CLI tools that convert the file to a PostScript
# file, and then to a PDF (enscript and ps2pdf).
#
# Options:
#       -h | --help
#           Usage message
#       -f | --filename
#           The name of the file to look for inside all the directories
#       -o | --output
#           The directory where the PDFs will be made. If the dir doesn't
#           exist, a new dir will be made in the current dir
#       -s | --single
#           Flag used to indicate that only a single file needs to be converted
#           Takes 2 params: path to file and name of pdf file (no ext needed)
#
# author:
#       scevallos (Sebastian)
# usage:
#       ./make_pdfs -f lab01 -o lab01_pdfs

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -h|--help)
        echo "Usage: ./make_pdfs -f <filename> -o <output_dir>"
        exit
     ;;
    -f|--filename)
        FILENAME="$2"
        shift # past argument
        shift # past value
     ;;
    -o|--output)
        OUTPUT_DIR="$2"
        shift # past argument
        shift # past value
     ;;
    -s|--single)
        SINGLE="$2"
        NAME="$3"
        shift
        shift
        shift
     ;;
    *)    # unknown option
        echo "Unknown option: $1"
        echo "Usage: ./make_pdfs -f <filename> -o <output_dir>"
        exit
    ;;
esac
done

# convert for single student
if [ "$SINGLE" -a "$NAME" ]; then
    echo "only converting $SINGLE"
    enscript -p "temp.ps" "$SINGLE" && ps2pdf temp.ps "$NAME" && rm temp.ps
    exit
fi

# Handling filename
if [ -z "$FILENAME" ]; then
    echo "Please supply filename (e.g. \"lab01\")"
    exit
fi

# Handling output dir stuff
if [ -z "$OUTPUT_DIR" ]; then
    # No output dir specified --> make some dir w/ PDFs in current dir 
    OUTPUT_DIR="output"
    mkdir "output"
elif [ ! -d "$OUTPUT_DIR" ]; then
    # A dir with $OUTPUT_DIR name doesn't exist --> make it
    mkdir "$OUTPUT_DIR"
fi

# used to help w "lab01" vs "Lab01"
capped=$(echo -n "${FILENAME:0:1}" | tr "[:lower:]" "[:upper:]"; echo -n "${FILENAME:1}")

# For each dir in current dir
for D in *; do
    # if dir and if there is a regular file w/ $FILENAME in there
    if [ -d "${D}" ]; then
       if [ -f "$D/$FILENAME.py" ]; then
           # convert to PS then to PDF. remove intermediate PS file afterwards
           enscript -p "$D/temp.ps" "$D/$FILENAME.py" && ps2pdf "$D/temp.ps" "$OUTPUT_DIR/$D-$FILENAME.pdf" && rm "$D/temp.ps"
       elif [ -f "$D/$capped.py" ]; then
           # catching capitalized first letter
           enscript -p "$D/temp.ps" "$D/$capped.py" && ps2pdf "$D/temp.ps" "$OUTPUT_DIR/$D-$FILENAME.pdf" && rm "$D/temp.ps"
       else
           echo "$D" >> "nofilelist.txt"
       fi
    fi
done
