#!/bin/bash
#
FILENAME=$1
for D in *; do
    # check if file is not a directory
    if [ ! -d "${D}" ]; then
        echo "$D is not a directory" >> "nofilelist.txt"
    # if it's a dir, check if there's a file w FILENAME name inside
    elif [ !-f "$D/$FILENAME.py" ]; then
        echo "$D doesn't have a $FILENAME file inside" >> "nofilelist.txt"
    fi
done
