#!/bin/bash
#
FILENAME=$1
for D in *; do
    # if dir and if there is a regular file w/ $FILENAME in there
    if [ ! -d "${D}" ]; then
        echo "$D is not a directory" >> "nofilelist.txt"
    elif [ !-f "$D/$FILENAME.py" ]; then
        echo "$D doesn't have a $FILENAME file inside" >> "nofilelist.txt"
    fi
done
